# Generated by Django 4.2.2 on 2023-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('ad_id', models.CharField(max_length=255)),
                ('name_author', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=400)),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=250)),
                ('platforms', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
            ],
        ),
    ]
