# Generated by Django 4.2.2 on 2023-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTypeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ad Type',
                'verbose_name_plural': 'Ad Types',
            },
        ),
        migrations.CreateModel(
            name='CountrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
