# Generated by Django 4.2.2 on 2023-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0002_adtypesettings_countrysettings_alter_ad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adtypesettings',
            options={'verbose_name': 'Select Ad Type', 'verbose_name_plural': 'Settings Ad Types'},
        ),
        migrations.AlterModelOptions(
            name='countrysettings',
            options={'verbose_name': 'Select Country', 'verbose_name_plural': 'Settings Countries'},
        ),
        migrations.AddField(
            model_name='ad',
            name='impressions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='predicted_audience_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name_author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='platforms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
